#!/bin/sh

# ┌─┐┌─┐┬─┐┌─┐┌─┐┌┐┌┌─┐┬ ┬┌─┐┌┬┐
# └─┐│  ├┬┘├┤ ├┤ │││└─┐├─┤│ │ │ 
# └─┘└─┘┴└─└─┘└─┘┘└┘└─┘┴ ┴└─┘ ┴ 

# author	Niraj
# github	niraj998

# ┌─┐┌─┐┌┐┌┌─┐┬┌─┐┬ ┬┬─┐┌─┐┌┬┐┬┌─┐┌┐┌┌─┐
# │  │ ││││├┤ ││ ┬│ │├┬┘├─┤ │ ││ ││││└─┐
# └─┘└─┘┘└┘└  ┴└─┘└─┘┴└─┴ ┴ ┴ ┴└─┘┘└┘└─┘

# icon for notification
icon=~/.config/rofi/screen/screen.png
# rofi config
roficonfig=~/.config/rofi/screen/config.rasi

# ┬─┐┌─┐┌─┐┬
# ├┬┘│ │├┤ │
# ┴└─└─┘└  ┴

screen1=$(xrandr -q | grep "connected" | awk '/ connected/ {print $1}' | head -n 1)
screen2=$(xrandr -q | grep "connected" | awk '/ connected/ {print $1}' | tail -n 1)

Laptop=""
Monitor=""
Dualscreen=""

rofiopt="$Laptop\n$Monitor\n$Dualscreen"
rofi=$(printf "$rofiopt" | rofi -config $roficonfig -dmenu -i )
[ -z "$rofi" ] && exit

[ "$screen1" = "$screen2" ] && notify-send -i "$icon" "Sceond Screen is not connected" && exit

case $rofi in 
	$Laptop)
	xrandr --output $screen1 --auto
	xrandr --output $screen2 --off
	bspc wm -r
	;;

	$Monitor)
	xrandr --output $screen2 --auto
	xrandr --output $screen1 --off
	bspc wm -r
	;;

  $Dualscreen)
	xrandr --output $screen1 --auto
	xrandr --output $screen2 --right-of $screen1 --auto
	bspc wm -r
esac
