#!/bin/sh

themedir="$HOME/.config/rofi/Themes"

themelist=$(ls -d */ | cut -d "/" -f1)

cat <<- EOF
Change Theme for all the Rofi

Available Themes: 
$themelist

Type theme you want to use:
EOF

read -r theme

colorlist=$(ls "$themedir/$theme" | cut -d "." -f1)

cat <<- EOF
Choose from Available Colors

Available Colors:
$colorlist

Type color you want to use:
EOF
read -r color

cat $themedir/$theme/$color.rasi > $themedir/style.rasi && echo "Done"
